import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Analytics from "@/components/Analytics";
import NavbarMinimal from "@/app/(sections)/Navbar/NavbarMinimal";
import NavCtaBridge from "@/app/(sections)/Navbar/NavCtaBridge";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "optional",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Analytics />
        <NavbarMinimal />
        <NavCtaBridge />
        {children}
      </body>
    </html>
  );
}
